### ISSUE TITLE
CRC and Class Diagrams

### ISSUE THREAD

**Issue by mud2man** [team-n3m/n3m#1]
The first version of CRC and Class Diagrams for party.io
CRC Cards:
![crc](https://cloud.githubusercontent.com/assets/18586620/19584520/270cf576-9713-11e6-9c33-34e80ce68e4e.png)

Class List:
![classes](https://cloud.githubusercontent.com/assets/22421121/19581715/17458b8c-96fd-11e6-9a24-af7295d89239.jpg)

Class Relationships:
![class relationships](https://cloud.githubusercontent.com/assets/22421121/19581751/4b7ea01e-96fd-11e6-826a-6a240d3b03f6.jpg)

**Comment by MIKEMAKRIS** [comment]
Updated class diagram

![classes](https://cloud.githubusercontent.com/assets/22421121/19955516/80e8f758-a158-11e6-8704-9b226b1b3faa.jpg)

![class relationships](https://cloud.githubusercontent.com/assets/22421121/19955603/29f427e6-a159-11e6-989d-900ec430a6cc.jpg)

**Comment by fanmin1010** [comment]
Updated CRC card and class diagrams after the first iteration.
Overflowed classes are marked.

<hr/>

class diagrams
![classes](https://cloud.githubusercontent.com/assets/12806520/20239753/b8a282fc-a8d5-11e6-9888-7a9439bb3906.png)

<hr/>

CRC cards
![class relationships](https://cloud.githubusercontent.com/assets/12806520/20239754/c0266c96-a8d5-11e6-9852-0054c9d26aab.png)

**Comment by MIKEMAKRIS** [comment]
**# Second Iteration** 
Class Diagrams
![classes](https://cloud.githubusercontent.com/assets/22421121/20398711/72be2c6a-acbc-11e6-9ace-c56d3b0e0517.png)

Class Relationships
![class relationships](https://cloud.githubusercontent.com/assets/22421121/20398664/48894b46-acbc-11e6-8da6-a45efbd885be.png)
