### ISSUE TITLE
add all test cases that caused failures during black box testing demo

### ISSUE THREAD

**Issue by morrishopkins** [team-n3m/n3m#19]
All of the user testing that failed.

**Comment by morrishopkins** [comment]
Here are the points I noted down today:
403 on adding non existent user as friend
403 on is_token_valid
On success, you could return 202
500 on empty password
Password length not checked on backend
200 on user creation
User can be created without email
Was also able to add a friend without email because of that
No email validation
User can be created without username
Username length validation
Once I click on the Profile, then no other link works
I forgot this earlier, but you could also ensure that a method that should accept POST only accepts POST and not GET and any other methods.

**Comment by fanmin1010** [comment]
Just checked, all working nicely now.
